# Generated by Django 2.2.7 on 2019-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_featuredproduct_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default=None, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default=None, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default=None, upload_to='product_images'),
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
