# Generated by Django 2.2.7 on 2019-12-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191215_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Tag'),
        ),
    ]
