# Generated by Django 2.2.7 on 2019-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekoutHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=5)),
                ('town', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('other_notes', models.TextField(max_length=300)),
            ],
        ),
    ]
