# Generated by Django 2.2.7 on 2020-01-02 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191231_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='chekouthistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
