# Generated by Django 2.2.7 on 2020-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_chekouthistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chekouthistory',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
