# Generated by Django 2.2.7 on 2020-01-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_chekouthistory_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chekouthistory',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chekouthistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chekouthistory',
            name='other_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
